In [156]:
import numpy as np
import pandas as pd
from pandas import Series
import timeit

In [201]:
#Mehtode 1: Numpy
arr = np.array(input("Enter an array: "))
np.unique(arr)

Enter an array: [3, 6, 7, 3, 2, 5, 6, 2, 4, 2]


array([2, 3, 4, 5, 6, 7])

In [122]:
arr.shape

(10,)

In [235]:
arr = np.random.randint(input("Choose max value an array's element can have (integer): ")+1, 
                        size=(input("Choose dimension of the array (e.g. (5,3,20) for a 5 x 3 x 20 array): ")))
arr

Choose max value an array's element can have (integer): 1000
Choose dimension of the array (e.g. (5,3,20) for a 5 x 3 x 20 array): (3,5,10)


array([[[523, 189, 327, 769, 236, 581, 159, 198, 614, 504],
        [761, 949, 659,  28, 768, 682, 788, 220, 580, 862],
        [762,  54, 639, 427, 222, 144, 258, 319, 184, 126],
        [139, 871, 498, 146,   1, 824, 301, 860, 651,  87],
        [299,   8,  75, 366, 492, 397, 739, 275, 630, 346]],

       [[865, 636, 468, 273, 223,  36, 337, 484, 324, 758],
        [785, 372, 797,  80,  39, 493, 439, 144, 882, 941],
        [428,  38, 312, 811,  64, 280,  99, 279, 895, 736],
        [850, 598, 381, 784, 347, 863, 183, 741, 988, 720],
        [850, 607, 737, 427, 587, 479, 798, 428, 731, 382]],

       [[284, 233, 606, 972, 752, 277, 608, 982, 117, 242],
        [ 55,  75, 222, 136, 461, 462, 682, 590, 782, 761],
        [ 74, 108, 557, 857, 909,  29, 958, 107, 491, 194],
        [420, 704, 457, 118, 194, 723,  40, 481, 554, 406],
        [317, 430, 656, 519, 580, 161, 810, 269, 285, 222]]])

In [236]:
arr.shape

(3, 5, 10)

In [237]:
%timeit np.unique(arr)
np.unique(arr)

10000 loops, best of 3: 22.9 µs per loop


array([  1,   8,  28,  29,  36,  38,  39,  40,  54,  55,  64,  74,  75,
        80,  87,  99, 107, 108, 117, 118, 126, 136, 139, 144, 146, 159,
       161, 183, 184, 189, 194, 198, 220, 222, 223, 233, 236, 242, 258,
       269, 273, 275, 277, 279, 280, 284, 285, 299, 301, 312, 317, 319,
       324, 327, 337, 346, 347, 366, 372, 381, 382, 397, 406, 420, 427,
       428, 430, 439, 457, 461, 462, 468, 479, 481, 484, 491, 492, 493,
       498, 504, 519, 523, 554, 557, 580, 581, 587, 590, 598, 606, 607,
       608, 614, 630, 636, 639, 651, 656, 659, 682, 704, 720, 723, 731,
       736, 737, 739, 741, 752, 758, 761, 762, 768, 769, 782, 784, 785,
       788, 797, 798, 810, 811, 824, 850, 857, 860, 862, 863, 865, 871,
       882, 895, 909, 941, 949, 958, 972, 982, 988])

In [238]:
np.unique(arr).shape

(139,)

In [239]:
#Methode 2: pandas.unique(). Dafür muss Array jedoch in 1D vorliegen -> Umwandlung des 3D arrays in 1D. 
arr.ravel()

array([523, 189, 327, 769, 236, 581, 159, 198, 614, 504, 761, 949, 659,
        28, 768, 682, 788, 220, 580, 862, 762,  54, 639, 427, 222, 144,
       258, 319, 184, 126, 139, 871, 498, 146,   1, 824, 301, 860, 651,
        87, 299,   8,  75, 366, 492, 397, 739, 275, 630, 346, 865, 636,
       468, 273, 223,  36, 337, 484, 324, 758, 785, 372, 797,  80,  39,
       493, 439, 144, 882, 941, 428,  38, 312, 811,  64, 280,  99, 279,
       895, 736, 850, 598, 381, 784, 347, 863, 183, 741, 988, 720, 850,
       607, 737, 427, 587, 479, 798, 428, 731, 382, 284, 233, 606, 972,
       752, 277, 608, 982, 117, 242,  55,  75, 222, 136, 461, 462, 682,
       590, 782, 761,  74, 108, 557, 857, 909,  29, 958, 107, 491, 194,
       420, 704, 457, 118, 194, 723,  40, 481, 554, 406, 317, 430, 656,
       519, 580, 161, 810, 269, 285, 222])

In [240]:
#Test: Dimension des umgwandelten Arrays
arr.ravel().shape

(150,)

In [241]:
#series.unique() 
pd.unique(arr.ravel())

array([523, 189, 327, 769, 236, 581, 159, 198, 614, 504, 761, 949, 659,
        28, 768, 682, 788, 220, 580, 862, 762,  54, 639, 427, 222, 144,
       258, 319, 184, 126, 139, 871, 498, 146,   1, 824, 301, 860, 651,
        87, 299,   8,  75, 366, 492, 397, 739, 275, 630, 346, 865, 636,
       468, 273, 223,  36, 337, 484, 324, 758, 785, 372, 797,  80,  39,
       493, 439, 882, 941, 428,  38, 312, 811,  64, 280,  99, 279, 895,
       736, 850, 598, 381, 784, 347, 863, 183, 741, 988, 720, 607, 737,
       587, 479, 798, 731, 382, 284, 233, 606, 972, 752, 277, 608, 982,
       117, 242,  55, 136, 461, 462, 590, 782,  74, 108, 557, 857, 909,
        29, 958, 107, 491, 194, 420, 704, 457, 118, 723,  40, 481, 554,
       406, 317, 430, 656, 519, 161, 810, 269, 285])

In [242]:
#Test, ob genaso viele Elemente wie in np.unique()
pd.unique(arr.ravel()).shape

(139,)

In [243]:
#Methode 3: 
Series(arr.ravel()).unique()

array([523, 189, 327, 769, 236, 581, 159, 198, 614, 504, 761, 949, 659,
        28, 768, 682, 788, 220, 580, 862, 762,  54, 639, 427, 222, 144,
       258, 319, 184, 126, 139, 871, 498, 146,   1, 824, 301, 860, 651,
        87, 299,   8,  75, 366, 492, 397, 739, 275, 630, 346, 865, 636,
       468, 273, 223,  36, 337, 484, 324, 758, 785, 372, 797,  80,  39,
       493, 439, 882, 941, 428,  38, 312, 811,  64, 280,  99, 279, 895,
       736, 850, 598, 381, 784, 347, 863, 183, 741, 988, 720, 607, 737,
       587, 479, 798, 731, 382, 284, 233, 606, 972, 752, 277, 608, 982,
       117, 242,  55, 136, 461, 462, 590, 782,  74, 108, 557, 857, 909,
        29, 958, 107, 491, 194, 420, 704, 457, 118, 723,  40, 481, 554,
       406, 317, 430, 656, 519, 161, 810, 269, 285])

In [ ]:
#Vergleich Rechenzeiten np.unique VS pd.unique VS series.unique

In [227]:
a = np.random.randint(0, 1000, 10000)
%timeit np.unique(a)

1000 loops, best of 3: 623 µs per loop


In [228]:
%timeit pd.unique(a)

10000 loops, best of 3: 170 µs per loop


In [231]:
%timeit Series(a.ravel()).unique()

1000 loops, best of 3: 317 µs per loop


In [232]:
# "Normale" Python Codes



In [118]:
#Methode 4
#sehr ineffizenter Code aber dank Moore's Law kein Problem
def unique(array):
    temp = [False]*(max(array)+1)
    sorted_arr = []
    for i in array:
        temp[i] = i
    for i in temp:
        if type(i) is not bool:
            sorted_arr.append(i)
    return sorted_arr

In [119]:
arr = input("Enter an array: ")
%timeit unique(arr)
unique(arr)

Enter an array: 1024, 3, 4, 5, 3 ,1024, 6
10000 loops, best of 3: 177 µs per loop


[3, 4, 5, 6, 1024]

In [109]:
#Methode 5
def unique(array):
    sorted_arr = []
    for i in array:
        if i not in sorted_arr:
            sorted_arr.append(i)
    return sorted_arr

In [117]:
%timeit unique([1024, 3, 4, 5, 3 ,1024, 6])
unique([1024, 3, 4, 5, 3 ,1024, 6])

The slowest run took 6.28 times longer than the fastest. This could mean that an intermediate result is being cached 
10000 loops, best of 3: 179 µs per loop


[3, 4, 5, 6, 1024]