In [156]:
import numpy as np
import pandas as pd
from pandas import Series
import timeit

In [201]:
#Mehtode 1: Numpy
arr = np.array(input("Enter an array: "))
np.unique(arr)

Enter an array: [3, 6, 7, 3, 2, 5, 6, 2, 4, 2]


array([2, 3, 4, 5, 6, 7])

In [122]:
arr.shape

(10,)

In [202]:
arr = np.random.randint(input("Choose max value an array's element can have (integer): ")+1, 
                        size=(input("Choose dimension of the array (e.g. (5,3,20) for a 5 x 3 x 20 array)")))
arr

Choose max value an array's element can have (integer): 1000
Choose dimension of the array (e.g. (5,3,20) for a 5 x 3 x 20 array)(3,5,10)


array([[[760,  43, 321, 509,  74, 446, 439,  74, 205,  79],
        [386, 121,  50, 749, 665, 666, 892, 500, 691, 159],
        [871, 559, 694, 216, 856, 171, 804, 996, 507, 521],
        [526,   8, 838, 233, 783, 530, 477, 300, 633, 309],
        [700, 742,   5, 128, 766, 169, 437, 996, 602, 285]],

       [[399, 590, 733, 566, 157, 966, 980, 205,  91, 423],
        [444, 585, 694, 574, 266, 606, 249, 168, 653,  87],
        [725, 268, 634, 796, 111, 132,  16, 518, 759, 446],
        [898, 340, 430, 131, 437, 276, 199, 687, 656,  93],
        [535, 787,   4, 503, 983, 381, 415, 145, 586,  52]],

       [[787, 992, 835, 251, 661, 248, 796, 941, 976,  76],
        [419, 705, 505, 526, 509, 625, 831, 467,   1, 182],
        [971, 789, 612, 884,  11, 730, 299, 827, 489, 224],
        [955, 182, 986, 259, 289,  90, 843,  23, 410, 314],
        [984, 763, 747, 930, 250, 863, 509, 493, 918, 422]]])

In [203]:
arr.shape

(3, 5, 10)

In [204]:
%timeit np.unique(arr)
np.unique(arr)

The slowest run took 5.18 times longer than the fastest. This could mean that an intermediate result is being cached 
10000 loops, best of 3: 22.8 µs per loop


array([  1,   4,   5,   8,  11,  16,  23,  43,  50,  52,  74,  76,  79,
        87,  90,  91,  93, 111, 121, 128, 131, 132, 145, 157, 159, 168,
       169, 171, 182, 199, 205, 216, 224, 233, 248, 249, 250, 251, 259,
       266, 268, 276, 285, 289, 299, 300, 309, 314, 321, 340, 381, 386,
       399, 410, 415, 419, 422, 423, 430, 437, 439, 444, 446, 467, 477,
       489, 493, 500, 503, 505, 507, 509, 518, 521, 526, 530, 535, 559,
       566, 574, 585, 586, 590, 602, 606, 612, 625, 633, 634, 653, 656,
       661, 665, 666, 687, 691, 694, 700, 705, 725, 730, 733, 742, 747,
       749, 759, 760, 763, 766, 783, 787, 789, 796, 804, 827, 831, 835,
       838, 843, 856, 863, 871, 884, 892, 898, 918, 930, 941, 955, 966,
       971, 976, 980, 983, 984, 986, 992, 996])

In [205]:
np.unique(arr).shape

(138,)

In [213]:
#Methode 2: pandas.unique(). Dafür muss Array jedoch in 1D vorliegen -> Umwandlung des 3D arrays in 1D. 
arr.ravel()

array([760,  43, 321, 509,  74, 446, 439,  74, 205,  79, 386, 121,  50,
       749, 665, 666, 892, 500, 691, 159, 871, 559, 694, 216, 856, 171,
       804, 996, 507, 521, 526,   8, 838, 233, 783, 530, 477, 300, 633,
       309, 700, 742,   5, 128, 766, 169, 437, 996, 602, 285, 399, 590,
       733, 566, 157, 966, 980, 205,  91, 423, 444, 585, 694, 574, 266,
       606, 249, 168, 653,  87, 725, 268, 634, 796, 111, 132,  16, 518,
       759, 446, 898, 340, 430, 131, 437, 276, 199, 687, 656,  93, 535,
       787,   4, 503, 983, 381, 415, 145, 586,  52, 787, 992, 835, 251,
       661, 248, 796, 941, 976,  76, 419, 705, 505, 526, 509, 625, 831,
       467,   1, 182, 971, 789, 612, 884,  11, 730, 299, 827, 489, 224,
       955, 182, 986, 259, 289,  90, 843,  23, 410, 314, 984, 763, 747,
       930, 250, 863, 509, 493, 918, 422])

In [215]:
#Test: Dimension des umgwandelten Arrays
arr.ravel().shape

(150,)

In [216]:
#series.unique() 
pd.unique(arr.ravel())

array([760,  43, 321, 509,  74, 446, 439, 205,  79, 386, 121,  50, 749,
       665, 666, 892, 500, 691, 159, 871, 559, 694, 216, 856, 171, 804,
       996, 507, 521, 526,   8, 838, 233, 783, 530, 477, 300, 633, 309,
       700, 742,   5, 128, 766, 169, 437, 602, 285, 399, 590, 733, 566,
       157, 966, 980,  91, 423, 444, 585, 574, 266, 606, 249, 168, 653,
        87, 725, 268, 634, 796, 111, 132,  16, 518, 759, 898, 340, 430,
       131, 276, 199, 687, 656,  93, 535, 787,   4, 503, 983, 381, 415,
       145, 586,  52, 992, 835, 251, 661, 248, 941, 976,  76, 419, 705,
       505, 625, 831, 467,   1, 182, 971, 789, 612, 884,  11, 730, 299,
       827, 489, 224, 955, 986, 259, 289,  90, 843,  23, 410, 314, 984,
       763, 747, 930, 250, 863, 493, 918, 422])

In [217]:
#Test, ob genaso viele Elemente wie in np.unique()
pd.unique(arr.ravel()).shape

(138,)

In [226]:
#Methode 3: 
Series(arr.ravel()).unique()

array([760,  43, 321, 509,  74, 446, 439, 205,  79, 386, 121,  50, 749,
       665, 666, 892, 500, 691, 159, 871, 559, 694, 216, 856, 171, 804,
       996, 507, 521, 526,   8, 838, 233, 783, 530, 477, 300, 633, 309,
       700, 742,   5, 128, 766, 169, 437, 602, 285, 399, 590, 733, 566,
       157, 966, 980,  91, 423, 444, 585, 574, 266, 606, 249, 168, 653,
        87, 725, 268, 634, 796, 111, 132,  16, 518, 759, 898, 340, 430,
       131, 276, 199, 687, 656,  93, 535, 787,   4, 503, 983, 381, 415,
       145, 586,  52, 992, 835, 251, 661, 248, 941, 976,  76, 419, 705,
       505, 625, 831, 467,   1, 182, 971, 789, 612, 884,  11, 730, 299,
       827, 489, 224, 955, 986, 259, 289,  90, 843,  23, 410, 314, 984,
       763, 747, 930, 250, 863, 493, 918, 422])

In [ ]:
#Vergleich Rechenzeiten np.unique VS pd.unique VS series.unique

In [227]:
a = np.random.randint(0, 1000, 10000)
%timeit np.unique(a)

1000 loops, best of 3: 623 µs per loop


In [228]:
%timeit pd.unique(a)

10000 loops, best of 3: 170 µs per loop


In [231]:
%timeit Series(a.ravel()).unique()

1000 loops, best of 3: 317 µs per loop


In [232]:
# "Normale" Python Codes



In [118]:
#Methode 4
#sehr ineffizenter Code aber dank Moore's Law kein Problem
def unique(array):
    temp = [False]*(max(array)+1)
    sorted_arr = []
    for i in array:
        temp[i] = i
    for i in temp:
        if type(i) is not bool:
            sorted_arr.append(i)
    return sorted_arr

In [119]:
arr = input("Enter an array: ")
%timeit unique(arr)
unique(arr)

Enter an array: 1024, 3, 4, 5, 3 ,1024, 6
10000 loops, best of 3: 177 µs per loop


[3, 4, 5, 6, 1024]

In [109]:
#Methode 5
def unique(array):
    sorted_arr = []
    for i in array:
        if i not in sorted_arr:
            sorted_arr.append(i)
    return sorted_arr

In [117]:
%timeit unique([1024, 3, 4, 5, 3 ,1024, 6])
unique([1024, 3, 4, 5, 3 ,1024, 6])

The slowest run took 6.28 times longer than the fastest. This could mean that an intermediate result is being cached 
10000 loops, best of 3: 179 µs per loop


[3, 4, 5, 6, 1024]