In [257]:
import numpy as np
import pandas as pd
from pandas import Series
import timeit, time

In [264]:
#Mehtode 1: Numpy. Einzelne Schritte zur Erklärung siehe im Anschluss.
def find_unique_values_in_array():
    arr = np.random.randint(input("Choose max value an array's element can have (integer): ")+1, 
                        size=(input("Choose dimension of the array (e.g. (5,3,20) for a 5 x 3 x 20 array): ")))
    print "Array: ", arr
    start = time.time()
    np.unique(arr)
    end = time.time()
    say = "Dauer in Sekunden: ", end-start
    print "Sortiertes Array + Dauer:"
    return np.unique(arr), say

In [265]:
find_unique_values_in_array()

Choose max value an array's element can have (integer): 1000
Choose dimension of the array (e.g. (5,3,20) for a 5 x 3 x 20 array): (5,4,2,3)
Array:  [[[[183 242 744]
   [559 172 387]]

  [[408 282 839]
   [ 28 123 965]]

  [[ 65 891 918]
   [761 382 676]]

  [[376 501  64]
   [435 351 679]]]


 [[[908  56 660]
   [ 28 171 907]]

  [[819  36 871]
   [633  46 825]]

  [[131 207 657]
   [871 533 573]]

  [[392 366 797]
   [855 618 506]]]


 [[[455 883 100]
   [497 854 765]]

  [[336 591 352]
   [753  75 963]]

  [[797 370 273]
   [775 532 996]]

  [[916 780 425]
   [ 37 636 348]]]


 [[[ 96 817 565]
   [906 789 640]]

  [[688  28 213]
   [707 422 428]]

  [[384 647 987]
   [780 769 376]]

  [[341 536 778]
   [680 915 170]]]


 [[[344 937 882]
   [245 941 920]]

  [[345 691 103]
   [550 249 947]]

  [[ 39 363 506]
   [159 472   9]]

  [[840 200 210]
   [843 870 652]]]]
Sortiertes Array + Dauer:


(array([  9,  28,  36,  37,  39,  46,  56,  64,  65,  75,  96, 100, 103,
        123, 131, 159, 170, 171, 172, 183, 200, 207, 210, 213, 242, 245,
        249, 273, 282, 336, 341, 344, 345, 348, 351, 352, 363, 366, 370,
        376, 382, 384, 387, 392, 408, 422, 425, 428, 435, 455, 472, 497,
        501, 506, 532, 533, 536, 550, 559, 565, 573, 591, 618, 633, 636,
        640, 647, 652, 657, 660, 676, 679, 680, 688, 691, 707, 744, 753,
        761, 765, 769, 775, 778, 780, 789, 797, 817, 819, 825, 839, 840,
        843, 854, 855, 870, 871, 882, 883, 891, 906, 907, 908, 915, 916,
        918, 920, 937, 941, 947, 963, 965, 987, 996]),
 ('Dauer in Sekunden: ', 4.792213439941406e-05))

In [201]:
arr = np.array(input("Enter an array: "))
np.unique(arr)

Enter an array: [3, 6, 7, 3, 2, 5, 6, 2, 4, 2]


array([2, 3, 4, 5, 6, 7])

In [122]:
arr.shape

(10,)

In [267]:
arr = np.random.randint(input("Choose max value an array's element can have (integer): ")+1, 
                        size=(input("Choose dimension of the array (e.g. (5,3,20) for a 5 x 3 x 20 array): ")))
arr

Choose max value an array's element can have (integer): 1000
Choose dimension of the array (e.g. (5,3,20) for a 5 x 3 x 20 array): (3,5,10)


array([[[199, 277, 197, 399, 397, 722, 139, 301, 229, 791],
        [229, 137, 865, 257,  71, 861, 541, 566, 572, 262],
        [ 58, 629, 405, 606, 522,  70, 564,  17, 553, 228],
        [494,   1, 203, 414, 177, 366, 643, 224, 122, 809],
        [182, 627, 361, 909, 262, 333, 314, 825,  20, 809]],

       [[186, 614, 132,  96, 622, 172, 675, 949, 292, 539],
        [158, 426, 517, 989,  50,  54, 844, 340, 163, 257],
        [770,  74,  67, 546, 390, 371, 155, 662,  37, 350],
        [502, 999, 377, 610, 645, 317, 548, 620, 433,  66],
        [119, 979, 937, 136,  49, 988, 926, 270, 380, 800]],

       [[629, 917, 823,  59, 563, 991, 269, 190,  92, 741],
        [668, 881,  19, 611, 983, 881, 882, 722, 471, 116],
        [416, 979, 590, 116, 122, 251, 102, 545, 574, 792],
        [320, 625, 735, 815, 747,  94, 823, 839, 296, 315],
        [413, 771, 408, 824, 606, 908, 141, 758, 233, 630]]])

In [268]:
arr.shape

(3, 5, 10)

In [269]:
%timeit np.unique(arr)
np.unique(arr)

10000 loops, best of 3: 22.7 µs per loop


array([  1,  17,  19,  20,  37,  49,  50,  54,  58,  59,  66,  67,  70,
        71,  74,  92,  94,  96, 102, 116, 119, 122, 132, 136, 137, 139,
       141, 155, 158, 163, 172, 177, 182, 186, 190, 197, 199, 203, 224,
       228, 229, 233, 251, 257, 262, 269, 270, 277, 292, 296, 301, 314,
       315, 317, 320, 333, 340, 350, 361, 366, 371, 377, 380, 390, 397,
       399, 405, 408, 413, 414, 416, 426, 433, 471, 494, 502, 517, 522,
       539, 541, 545, 546, 548, 553, 563, 564, 566, 572, 574, 590, 606,
       610, 611, 614, 620, 622, 625, 627, 629, 630, 643, 645, 662, 668,
       675, 722, 735, 741, 747, 758, 770, 771, 791, 792, 800, 809, 815,
       823, 824, 825, 839, 844, 861, 865, 881, 882, 908, 909, 917, 926,
       937, 949, 979, 983, 988, 989, 991, 999])

In [270]:
np.unique(arr).shape

(138,)

In [271]:
#Methode 2: pandas.unique(). Dafür muss Array jedoch in 1D vorliegen -> Umwandlung des 3D arrays in 1D. 
arr.ravel()

array([199, 277, 197, 399, 397, 722, 139, 301, 229, 791, 229, 137, 865,
       257,  71, 861, 541, 566, 572, 262,  58, 629, 405, 606, 522,  70,
       564,  17, 553, 228, 494,   1, 203, 414, 177, 366, 643, 224, 122,
       809, 182, 627, 361, 909, 262, 333, 314, 825,  20, 809, 186, 614,
       132,  96, 622, 172, 675, 949, 292, 539, 158, 426, 517, 989,  50,
        54, 844, 340, 163, 257, 770,  74,  67, 546, 390, 371, 155, 662,
        37, 350, 502, 999, 377, 610, 645, 317, 548, 620, 433,  66, 119,
       979, 937, 136,  49, 988, 926, 270, 380, 800, 629, 917, 823,  59,
       563, 991, 269, 190,  92, 741, 668, 881,  19, 611, 983, 881, 882,
       722, 471, 116, 416, 979, 590, 116, 122, 251, 102, 545, 574, 792,
       320, 625, 735, 815, 747,  94, 823, 839, 296, 315, 413, 771, 408,
       824, 606, 908, 141, 758, 233, 630])

In [272]:
#Test: Dimension des umgwandelten Arrays
arr.ravel().shape

(150,)

In [273]:
pd.unique(arr.ravel())

array([199, 277, 197, 399, 397, 722, 139, 301, 229, 791, 137, 865, 257,
        71, 861, 541, 566, 572, 262,  58, 629, 405, 606, 522,  70, 564,
        17, 553, 228, 494,   1, 203, 414, 177, 366, 643, 224, 122, 809,
       182, 627, 361, 909, 333, 314, 825,  20, 186, 614, 132,  96, 622,
       172, 675, 949, 292, 539, 158, 426, 517, 989,  50,  54, 844, 340,
       163, 770,  74,  67, 546, 390, 371, 155, 662,  37, 350, 502, 999,
       377, 610, 645, 317, 548, 620, 433,  66, 119, 979, 937, 136,  49,
       988, 926, 270, 380, 800, 917, 823,  59, 563, 991, 269, 190,  92,
       741, 668, 881,  19, 611, 983, 882, 471, 116, 416, 590, 251, 102,
       545, 574, 792, 320, 625, 735, 815, 747,  94, 839, 296, 315, 413,
       771, 408, 824, 908, 141, 758, 233, 630])

In [274]:
#Test, ob genaso viele Elemente wie in np.unique()
pd.unique(arr.ravel()).shape

(138,)

In [275]:
#Methode 3: Series.unique() 
Series(arr.ravel()).unique()

array([199, 277, 197, 399, 397, 722, 139, 301, 229, 791, 137, 865, 257,
        71, 861, 541, 566, 572, 262,  58, 629, 405, 606, 522,  70, 564,
        17, 553, 228, 494,   1, 203, 414, 177, 366, 643, 224, 122, 809,
       182, 627, 361, 909, 333, 314, 825,  20, 186, 614, 132,  96, 622,
       172, 675, 949, 292, 539, 158, 426, 517, 989,  50,  54, 844, 340,
       163, 770,  74,  67, 546, 390, 371, 155, 662,  37, 350, 502, 999,
       377, 610, 645, 317, 548, 620, 433,  66, 119, 979, 937, 136,  49,
       988, 926, 270, 380, 800, 917, 823,  59, 563, 991, 269, 190,  92,
       741, 668, 881,  19, 611, 983, 882, 471, 116, 416, 590, 251, 102,
       545, 574, 792, 320, 625, 735, 815, 747,  94, 839, 296, 315, 413,
       771, 408, 824, 908, 141, 758, 233, 630])

In [ ]:
#Vergleich Rechenzeiten np.unique VS pd.unique VS series.unique

In [227]:
a = np.random.randint(0, 1000, 10000)
%timeit np.unique(a)

1000 loops, best of 3: 623 µs per loop


In [228]:
%timeit pd.unique(a)

10000 loops, best of 3: 170 µs per loop


In [231]:
%timeit Series(a.ravel()).unique()

1000 loops, best of 3: 317 µs per loop


In [232]:
# "Normale" Python Codes



In [118]:
#Methode 4
#sehr ineffizenter Code aber dank Moore's Law kein Problem
def unique(array):
    temp = [False]*(max(array)+1)
    sorted_arr = []
    for i in array:
        temp[i] = i
    for i in temp:
        if type(i) is not bool:
            sorted_arr.append(i)
    return sorted_arr

In [119]:
arr = input("Enter an array: ")
%timeit unique(arr)
unique(arr)

Enter an array: 1024, 3, 4, 5, 3 ,1024, 6
10000 loops, best of 3: 177 µs per loop


[3, 4, 5, 6, 1024]

In [109]:
#Methode 5
def unique(array):
    sorted_arr = []
    for i in array:
        if i not in sorted_arr:
            sorted_arr.append(i)
    return sorted_arr

In [117]:
%timeit unique([1024, 3, 4, 5, 3 ,1024, 6])
unique([1024, 3, 4, 5, 3 ,1024, 6])

The slowest run took 6.28 times longer than the fastest. This could mean that an intermediate result is being cached 
10000 loops, best of 3: 179 µs per loop


[3, 4, 5, 6, 1024]