In [4]:
import numpy as np
import pandas as pd

In [62]:
arr = np.array(input("Enter an array: "))
sorted_arr = np.unique(arr)
sorted_arr

Enter an array: [3, 6, 7, 3, 2, 5, 6, 2, 4, 2]


array([2, 3, 4, 5, 6, 7])

In [63]:
arr.shape

(10,)

In [82]:
arr = np.random.randint(input("Choose max value an array's element can have (integer): ")+1, size=(input("Choose dimension of the array (e.g. (5,3,20) for a 5 x 3 x 20 array)")))
arr

Choose max value an array's element can have (integer): 1000
Choose dimension of the array (e.g. (5,3,20) for a 5 x 3 x 20 array)3,5,8


array([[[676, 867, 483,  17, 696, 769, 454, 829],
        [942, 390, 103, 262,  93, 586, 403, 721],
        [616, 484, 838, 733,  15, 339, 214, 122],
        [ 70, 538, 595, 368, 217, 417, 634, 231],
        [577, 631, 660, 677, 698, 798, 219, 624]],

       [[666,  77,  15, 172, 510, 432, 851, 511],
        [887, 446, 692, 418, 517, 837, 167, 155],
        [ 96, 437, 850, 705, 542, 883, 983, 164],
        [625, 568, 909,  41, 351, 127, 360, 876],
        [334, 657, 916, 437, 700, 534, 625, 376]],

       [[112, 365, 888, 361, 208, 395, 151, 529],
        [ 19, 437, 805, 175, 296, 563, 769, 437],
        [819, 197, 235,  22, 799, 156, 395, 810],
        [311, 111, 545, 513, 458, 386, 636, 269],
        [847, 120, 804,  24, 219, 946, 319, 434]]])

In [83]:
np.unique(arr)

array([ 15,  17,  19,  22,  24,  41,  70,  77,  93,  96, 103, 111, 112,
       120, 122, 127, 151, 155, 156, 164, 167, 172, 175, 197, 208, 214,
       217, 219, 231, 235, 262, 269, 296, 311, 319, 334, 339, 351, 360,
       361, 365, 368, 376, 386, 390, 395, 403, 417, 418, 432, 434, 437,
       446, 454, 458, 483, 484, 510, 511, 513, 517, 529, 534, 538, 542,
       545, 563, 568, 577, 586, 595, 616, 624, 625, 631, 634, 636, 657,
       660, 666, 676, 677, 692, 696, 698, 700, 705, 721, 733, 769, 798,
       799, 804, 805, 810, 819, 829, 837, 838, 847, 850, 851, 867, 876,
       883, 887, 888, 909, 916, 942, 946, 983])

In [85]:
a = np.random.randint(0, 1000, 10000)
%timeit np.unique(a)

1000 loops, best of 3: 613 µs per loop


In [32]:
%timeit pd.unique(a)

NameError: global name 'a' is not defined

In [107]:
def unique(array):
    temp = [False]*(max(array)+1)
    print len(temp)
    sorted_arr = []
    print temp
    for i in array:
        temp[i] = i
    for i in temp:
        if type(i) is not bool:
            sorted_arr.append(i)
    return sorted_arr

In [108]:
arr = np.array(input("Enter an array: "))
unique(arr)


Enter an array: 1024, 3, 4, 5, 3 ,1024, 6
1025
[False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, 

[3, 4, 5, 6, 1024]